spring.application.name=mongocrudspring
spring.data.mongodb.uri=mongodb://localhost:27017/testdb

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=group_id
app.kafka.topic=user-events
